<?php
//----------------------------------------- SAGEC ------------------------------------------------

// This file is part of SAGEC67 Copyright (C) 2003 (Jean-Claude Bartier).
// SAGEC67 is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// SAGEC67 is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// You should have received a copy of the GNU General Public License
// along with SAGEC67; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//----------------------------------------- SAGEC ----------------------------------------------
/**
 * date de création: 	18/08/2003
 * @author:			jcb/Leboeuf pp 84
 * description:		gestion de plusieurs langues dans l'application
 * @version:		$Id: globals_string_lang.php 32 2008-02-17 15:14:17Z jcb $
 * maj le:			20/08/2005
*/
//----------------------------------------------------------------------------------------------
//session_start(); // pour récupérer $langue

$string_lang = array(
	'A'=> array(	
		'FR'=> "à",
		'UK'=> "at",
		'GE'=> "um"),
	'A_PARTIR'=> array(	
		'FR'=> "à partir de ",
		'UK'=> "as from ",
		'GE'=> "ab "),
	'ADMINISTRATEUR'=> array(
		'FR'=> "Administrateur",
		'UK'=> "Administrator",
		'GE'=> "Verwalter"),
	'ADMINISTRATION'=> array(
		'FR'=> "Administration",
		'UK'=> "Administration",
		'GE'=> "Verwaltung"),
	'ADRESSE'=> array(	
		'FR'=> "Adresse",
		'UK'=> "Address",
		'GE'=> "Adresse"),
	'ADO'=> array(	
		'FR'=> "Adolescent",
		'UK'=> "Teenager",
		'GE'=> "Jugendlicher"),
	'ADULTE'=> array(	
		'FR'=> "Adulte",
		'UK'=> "Adult",
		'GE'=> "Erwachsene"),
	'ADULTE_ACCEPTE'=> array(	
		'FR'=> "Adultes acceptés",
		'UK'=> "Adults accepted",
		'GE'=> "Akzeptierte Erwachsene"),
	'ADULTE_VENTILE'=> array(	
		'FR'=> "Adultes ventilés",
		'UK'=> "Adults ventilated",
		'GE'=> "Erwachsene mit Beatmungsgeräte"),
	'ADULTE_N_VENTILE'=> array(	
		'FR'=> "Adultes non ventilés",
		'UK'=> "Adults no ventilated",
		'GE'=> "Erwachsene ohne Beatmungsgeräte"),
	'AFFECTE'=> array(	
		'FR'=> "Affecté",
		'UK'=> "Affected",
		'GE'=> "Betroffen"),
	'AGE'=> array(	
		'FR'=> "Age",
		'UK'=> "Age",
		'GE'=> "Alter"),
	'ALBANIE'=> array(	
		'FR'=> "Albanie",
		'UK'=> "Albania",
		'GE'=> "Albanien"),
	'ALGERIE'=> array(	
		'FR'=> "Algérie",
		'UK'=> "Algeria",
		'GE'=> "Algerien"),
	'ALL_ETATS'=> array(	
		'FR'=> "Tous",
		'UK'=> "All",
		'GE'=> "Alle"),
	'ALL_SERVICES'=> array(	
		'FR'=> "Tous les services",
		'UK'=> "All the services",
		'GE'=> "Alle"),
	'ALLEMAGNE'=> array(	
		'FR'=> "Allemagne",
		'UK'=> "Germany",
		'GE'=> "Deutschland"),
	'ALLEMAND'=> array(	
		'FR'=> "Allemand",
		'UK'=> "German",
		'GE'=> "Deutsch"),
	'AJOUTER_SERVICE'=> array(
		'FR'=> "Ajouter / Mettre à jour un service",
		'UK'=> "Add / Update a ward",
		'GE'=> "Addieren / Aktualisieren ein Station"),
	'AJOUTER_HOPITAL'=> array(	
		'FR'=> "Ajouter / Mettre à jour un hôpital",
		'UK'=> "Add / Update a hospital",
		'GE'=> "Addieren / Aktualisieren ein Krankenhaus"),
	'AJOUTER_VECTEUR'=> array(	
		'FR'=> "Ajouter / Modifier un vecteur",
		'UK'=> "To add/Modify a vector",
		'GE'=> "Hinzufügen/einen Vektor ändern"),
	'AJOUTER_MODIF_ORGANISME'=> array(	
		'FR'=> "Ajouter / Modifier un organisme",
		'UK'=> "Add/Modify an organization",
		'GE'=> "Hinzufügen/ändern einen Organisation"),
	'AJOUTER_MODIF_INTERVENANT'=> array(	
		'FR'=> "Ajouter / Modifier un intervenant",
		'UK'=> "Add/Modify an intervenant",
		'GE'=> "Hinzufügen/ändern einen intervenant"),
	'ALERTE'=> array(
		'FR'=> "Alerte",
		'UK'=> "Alarm",
		'GE'=> "Alarm"),
	'ANS'=> array(
		'FR'=> "ans",
		'UK'=> "years",
		'GE'=> "Jahren"),
	'ANGLAIS'=> array(	
		'FR'=> "Anglais",
		'UK'=> "British",
		'GE'=> "Englisch"),
	'ANNUAIRE'=> array(	
		'FR'=> "Annuaire",
		'UK'=> "Phone book",
		'GE'=> "Telephonnummern"),
	'ANTIBIOTIQUE'=> array(	
		'FR'=> "Antibiotiques",
		'UK'=> "Antibiotics",
		'GE'=> "Antibiotika"),
	'ANTIDOTE'=> array(
		'FR'=> "Antidotes",
		'UK'=> "Antidotes",
		'GE'=> "Gegengifte"),
	'A_PARTIR'=> array(
		'FR'=> "A partir de ",
		'UK'=> "from ",
		'GE'=> "ab "),
	'ARRIVE'=> array(	
		'FR'=> "Arrivé",
		'UK'=> "Arived",
		'GE'=> "Angekommen"),
	'ARTERIO'=> array(	
		'FR'=> "Artériographie",
		'UK'=> "Arteriography",
		'GE'=> "Arteriography"),
	'ASCENCEUR'=> array(	
		'FR'=> "Ascenceur",
		'UK'=> "Lift",
		'GE'=> "Fahrstuhl"),
	'ASM'=> array(	
		'FR'=> "ASM",
		'UK'=> "ASM",
		'GE'=> "ASM"),
	'ASSU'=> array(	
		'FR'=> "ASSU",
		'UK'=> "ASSU",
		'GE'=> "ASSU"),
	'AUCUNE'=> array(	
		'FR'=> "Aucune",
		'UK'=> "No",
		'GE'=> "Nein"),
	'AUTEUR'=> array(
		'FR'=> "Auteur",
		'UK'=> "Author",
		'GE'=> "Autor"),
	'AUTOBUS'=> array(
		'FR'=> "Autobus",
		'UK'=> "Bus",
		'GE'=> "Autobus"),
	'AUTOUR'=> array(
		'FR'=> "autour de",
		'UK'=> "around",
		'GE'=> "um"),
	'AUTORISE'=> array(
		'FR'=> " autorisés",
		'UK'=> " authorized",
		'GE'=> " befugt"),
	'AUTRE'=> array(
		'FR'=> " Autre",
		'UK'=> " Other",
		'GE'=> " Andere"),
	'AUTRICHE'=> array(	
		'FR'=> "Autriche",
		'UK'=> "Austria",
		'GE'=> "Österreich"),
	'AVEZ-VOUS'=> array(	
		'FR'=> "Avez-vous",
		'UK'=> "Did you have",
		'GE'=> "Haben Sie"),
	'AVION'=> array(	
		'FR'=> "Avion",
		'UK'=> "Plane",
		'GE'=> "Flugzeug"),
	'BATIMENT'=> array(
		'FR'=> "Batiment",
		'UK'=> "Building",
		'GE'=> "Gebäude"),
	'BEEPER'=> array(
		'FR'=> "beeper",
		'UK'=> "beeper",
		'GE'=> "beeper"),
	'BELGIQUE'=> array(	
		'FR'=> "Belgique",
		'UK'=> "Belgium",
		'GE'=> "Belgien"),
	'BESOINS_MAT'=> array(
		'FR'=> "Besoins en matériel",
		'UK'=> "Needs in equipment",
		'GE'=> "Bedürfnisse im Material"),
	'BESOINS_PER'=> array(
		'FR'=> "Besoins en personnel",
		'UK'=> "Needs in staff",
		'GE'=> "Bedürfnisse im Personal"),
	'BESOINS_URGENT'=> array(
		'FR'=> "Besoins urgents",
		'UK'=> "Urgent needs",
		'GE'=> "Dringender Bedarf"),
	'BIOCHIMIE'=> array(
		'FR'=> "Biochimie",
		'UK'=> "Biochemie",
		'GE'=> "Biokimie"),
	'BIP'=> array(
		'FR'=> "Bip",
		'UK'=> "Bip",
		'GE'=> "Bip"),
	'BLOC'=> array(	
		'FR'=> "BLOC OP",
		'UK'=> "OP ROOM",
		'GE'=> "OP"),
	'BLOCNOTE'=> array(
		'FR'=> "Main Courante",
		'UK'=> "Scratch pad",
		'GE'=> "Notizblock"),
	'BRÛLES'=> array(
		'FR'=> "BRÛLES",
		'UK'=> "BURN UNIT",
		'GE'=> "Brandopfer"),
	'BULGARIE'=> array(	
		'FR'=> "Bulgarie",
		'UK'=> "Bulgaria",
		'GE'=> "Bulgarien"),
	'CAISSON'=> array(
		'FR'=> "Caisson hyperbare",
		'UK'=> "Hyperbaric chamber",
		'GE'=> "Druckkammer"),
	'CARTOGRAPHIE'=> array(	
		'FR'=> "Cartographie",
		'UK'=> "Cartography",
		'GE'=> "Kartographie"),
	'CATC'=> array(	
		'FR'=> "Ambulance C",
		'UK'=> "Ambulance C",
		'GE'=> "KTW"),
	'CENTRALE'=> array(
		'FR'=> "Centrale d'appels",
		'UK'=> "Emergency Call Center",
		'GE'=> "Leitstelle"),
	'CENTRALES'=> array(
		'FR'=> "Centrale",
		'UK'=> "Central",
		'GE'=> "Zentral"),
	'CENTRE_DE_BRULES'=> array(
		'FR'=> "Centres de grands brûlés",
		'UK'=> "Burns centers",
		'GE'=> " Brandverletzten Zentrum"),
	'CENTRE_DE_BRULES_PROCHES'=> array(
		'FR'=> "Centres de grands brûlés les plus proches",
		'UK'=> "Closest Burns Centers",
		'GE'=> "Nähste Brandverletzten Zentrum"),
	'CHAMBRES_PP'=> array(
		'FR'=> "Chambres en pression positive",
		'UK'=> "Positive pressure rooms",
		'GE'=> "Positive Druckräume"),
	'CHAMBRES_PN'=> array(
		'FR'=> "Chambres en pression négative",
		'UK'=> "Negative pressure rooms",
		'GE'=> "Negative Druckräume"),
	'CHAMBRES_ST'=> array(
		'FR'=> "Chambres stériles",
		'UK'=> "Germ free rooms",
		'GE'=> "Steriles Zimmer"),
	'CHANTIER'=> array(
		'FR'=> "Chantier",
		'UK'=> "place of the accident",
		'GE'=> "Unfallort"),
	'CHANGER_MOTDEPASSE'=> array(
		'FR'=> "Changer votre mot de passe",
		'GE'=> "Ihr Kennwort ändern",
		'UK'=> "To modify your password"),
	'CHERCHER'=> array(	
		'FR'=> "Chercher",
		'UK'=> "Find",
		'GE'=> "Suchen"),
	'CHIRURGIE'=> array(
		'FR'=> "CHIRURGIE",
		'UK'=> "SURGERY",
		'GE'=> "CHIRURGIE"),
	'CHIR_CARD'=> array(
		'FR'=> "Chirurgie cardiaque",
		'UK'=> "Cardiac surgery",
		'GE'=> "Kardiale Chirurgie"),
	'CHIR_INF'=> array(
		'FR'=> "Chirurgie infantile",
		'UK'=> "Infantile surgery",
		'GE'=> "Infantile Chirurgie"),
	'CHIR_THO'=> array(
		'FR'=> "Chirurgie thoracique",
		'UK'=> "Thoracic surgery",
		'GE'=> "Brustchirurgie"),
	'CHIR_URO'=> array(
		'FR'=> "Chirurgie urologique",
		'UK'=> "Urologic surgery",
		'GE'=> "Urologische Chirurgie"),
	'CHIR_VASC'=> array(
		'FR'=> "Chirurgie vasculaire",
		'UK'=> "Vascular Surgery",
		'GE'=> "Gefäßchirurgie"),
	'CHIR_VISC'=> array(
		'FR'=> "Chirurgie viscérale",
		'UK'=> "Visceral surgery",
		'GE'=> "Eingeweidechirurgie"),
	'CIVILITE'=> array(
		'FR'=> "Civilité",
		'UK'=> "Civility",
		'GE'=> "Höflichkeit"),
	'CMIC'=> array(
		'FR'=> "CMIC",
		'UK'=> "Hazmat Unit",
		'GE'=> "CMIC"),
	'CMIR'=> array(
		'FR'=> "CMIR",
		'UK'=> "CMIR",
		'GE'=> "CMIR"),
	'COCHER'=> array(
		'FR'=> "Tout cocher",
		'UK'=> "Check all",
		'GE'=> "Check alles"),
	'CODE_SERVICE'=> array(	
		'FR'=> "Code service",
		'UK'=> "Ward number",
		'GE'=> "Station Kode"),
	'COMMUNE'=> array(
		'FR'=> "Commune",
		'UK'=> "Town",
		'GE'=> "Stadt"),
	'CONFIDENTIALITE_CONTACT'=> array(
		'FR'=> "Confidentialité du contact",
		'UK'=> "confidentiality of the contact",
		'GE'=> "Vertraulichkeit des Kontaktes"),
	'CONNEXION'=> array(	
		'FR'=> "Connexions",
		'UK'=> "Connections",
		'GE'=> "Verbindungen"),
	'CONTACT'=> array(	
		'FR'=> "Contact",
		'UK'=> "Contact",
		'GE'=> "Kontakt"),
	'CONTACT_NOUVEAU'=> array(	
		'FR'=> "Ajouter un nouveau contact",
		'UK'=> "Add a new contact",
		'GE'=> "Einen neuen Kontakt hinzufügen"),
	'COPIE'=> array(	
		'FR'=> "Copie pour",
		'UK'=> "Backup for",
		'GE'=> "Kopie an"),
	'CROATIE'=> array(
		'FR'=> "Croatie",
		'UK'=> "Croatia",
		'GE'=> "Kroatien"),
	'DATE'=> array(
		'FR'=> "Date",
		'UK'=> "Date",
		'GE'=> "Datum"),
	'DESTINATION'=> array(
		'FR'=> "Destination",
		'UK'=> "Destination",
		'GE'=> "Bestimmungsort"),
	'DCI'=> array(
		'FR'=> "DCI",
		'UK'=> "DCI",
		'GE'=> "DCI"),
	'DECOCHER'=> array(
		'FR'=> "Tout décocher",
		'UK'=> "Uncheck all",
		'GE'=> "Uncheck alles"),
	'DECONTAMINE'=> array(
		'FR'=> "Décontaminé",
		'UK'=> "decontaminated",
		'GE'=> "Entseucht"),
	'DEGATS'=> array(
		'FR'=> "Dégats",
		'UK'=> "Dégats",
		'GE'=> "Sachschaden"),
	'DELAI_ROUTE'=> array(	
		'FR'=> "Délai de route",
		'UK'=> "Period of road",
		'GE'=> "Frist von Weg"),
	'DEVELOPPEMENT_ENCOURS'=> array(	
		'FR'=> "Développement en cours",
		'UK'=> "Development in hand",
		'GE'=> "Laufende Entwicklung"),
	'DEVENIR'=> array(
		'FR'=> "Devenir",
		'UK'=> "to become",
		'GE'=> "Entstehung"),
	'DIALYSEUR'=> array(
		'FR'=> "Appareils de dialyse",
		'UK'=> "Dialysis machines",
		'GE'=> "Dialysegerät"),
	'DISPO_ACTUEL'=> array(	
		'FR'=> "Disponibilité actuelle",
		'UK'=> "Disponibilité actuelle",
		'GE'=> "Derzeitige Verfügbar"),
	'DISPO RADIO'=> array(	
		'FR'=> "Disponible radio",
		'UK'=> "Disponible radio",
		'GE'=> "Disponible radio"),
	'DISPONIBLE'=> array(	
		'FR'=> "Disponible",
		'UK'=> "Available",
		'GE'=> "Derzeitige Verfügbarkeit"),
	'DISTANCE'=> array(	
		'FR'=> "Distance",
		'UK'=> "Distance",
		'GE'=> "Distanz"),
	'DOC'=> array(
		'FR'=> "Doc ",
		'UK'=> "Doc ",
		'GE'=> "Dokumentation"),
	'DOMICILE'=> array(
		'FR'=> "Domicile",
		'UK'=> "Home",
		'GE'=> "Haus"),
	'DOSAGE'=> array(
		'FR'=> "Dosage",
		'UK'=> "Dosage",
		'GE'=> "Dosierung"),
	'ECHEC_CONNEXION'=> array(	
		'FR'=> "En cas d'impossibilité de connexion veuillez consulter votre administrateur.",
		'UK'=> "In the event of impossibility of connection please consult your administrator.",
		'GE'=> "Bei Verbindungsunmöglichkeit befragen Sie bitte Ihren Verwalter."),
	'ECHO'=> array(	
		'FR'=> "Echographie",
		'UK'=> "Echography",
		'GE'=> "Echography"),
	'EHPAD'=> array(	
		'FR'=> "EHPAD",
		'UK'=> "EHPAD",
		'GE'=> "EHPAD"),
	'ENFANT'=> array(	
		'FR'=> "Enfant",
		'UK'=> "Child",
		'GE'=> "Kinder"),
	'ENFANT_ACCEPTE'=> array(	
		'FR'=> "Enfants acceptés",
		'UK'=> "Child accepted",
		'GE'=> "Akzeptierte Kinder"),
	'ENFANT_VENTILE'=> array(	
		'FR'=> "Enfants ventilés",
		'UK'=> "Child ventilated",
		'GE'=> "Kinder mit Beatmungsgeräte"),
	'ENFANT_N_VENTILE'=> array(	
		'FR'=> "Enfants non ventilés",
		'UK'=> "Child non ventilated",
		'GE'=> "Kinder ohne Beatmungsgeräte"),
	'ENGAGE'=> array(	
		'FR'=> "Engagé",
		'UK'=> "Engaged",
		'GE'=> "Freiwillige"),
	'EQUIPE'=> array(	
		'FR'=> "équipe",
		'UK'=> "rescue team",
		'GE'=> "Rettungsteam"),
	'EN ROUTE'=> array(	
		'FR'=> "En route",
		'UK'=> "On the road",
		'GE'=> "On the road"),
	'ENREGISTREMENT'=> array(	
		'FR'=> "Vous êtes enregistré en tant qu'utilisateur n° ",
		'UK'=> "You are recorded as user n° ",
		'GE'=> "Sie werden registriert als Benutzer n° "),
	'ERREUR'=> array(	
		'FR'=> "Des erreurs ?",
		'UK'=> "Errors ?",
		'GE'=> "Fehler ?"),
	'_ERROR_AUTH_BADHEADER'=> array(	
		'FR'=> "Header absent ou paramètres manquants",
		'UK'=> "Bad or missing header argument/parameter",
		'GE'=> "Schlechte oder fehlende Überschrift argument/parameter"),
	'_ERROR_AUTH_USER'=> array(	
		'FR'=> "Utilisateur inconnu",
		'UK'=> "Wrong user",
		'GE'=> "Falscher Benutzer"),
	'_ERROR_AUTH_PW'=> array(	
		'FR'=> "Mot de passe erronné",
		'UK'=> "Wrong password",
		'GE'=> "Falsches Kennwort"),
	'_ERROR_AUTH_AREA'=> array(	
		'FR'=> "No permission for the protected area",
		'UK'=> "No permission for the protected area",
		'GE'=> "No permission for the protected area"),
	'_ERROR_AUTH_LOCKED'=> array(	
		'FR'=> "The user permission is locked",
		'UK'=> "The user permission is locked",
		'GE'=> "The user permission is locked"),
	'_ERROR_SQL_RESULT'=> array(	
		'FR'=> "The sql query failed",
		'UK'=> "The sql query failed",
		'GE'=> "The sql query failed"),
	'_ERROR_NO_RESULT'=> array(	
		'FR'=> "The sprocedure returned no result",
		'UK'=> "The sprocedure returned no result",
		'GE'=> "The sprocedure returned no result"),
	'_ERROR_PROC_NORESULT'=> array(	
		'FR'=> "The sprocedure is not supported",
		'UK'=> "The sprocedure is not supported",
		'GE'=> "The sprocedure is not supportedt"),
	'_ERROR_PROC_NOEXISTS'=> array(	
		'FR'=> "The sprocedure is not available",
		'UK'=> "The sprocedure is not available",
		'GE'=> "The sprocedure is not available"),
	'ET'=> array(
		'FR'=> "et",
		'UK'=> "and",
		'GE'=> "und"),
	'ETABLISSEMENT'=> array(
		'FR'=> "Etablissement",
		'UK'=> "Hospital",
		'GE'=> "Krankenhaus",
		'CH'=> "Spital"),
	'ETAGE'=> array(	
		'FR'=> "Etage",
		'UK'=> "Floor",
		'GE'=> "Stock"),
	'ETAT_MOYEN'=> array(	
		'FR'=> "Etat",
		'UK'=> "State",
		'GE'=> "State"),
	'EVAC'=> array(	
		'FR'=> "PRE",
		'UK'=> "Evacuation",
		'GE'=> "Abstransport"),
	'EVAC_EN_COURS'=> array(	
		'FR'=> "Evacuation en cours",
		'UK'=> "Evacuation in progress",
		'GE'=> "Laufende Transport"),
	'EVAC EN COURS'=> array(	
		'FR'=> "Evacuation en cours",
		'UK'=> "Evacuation in progress",
		'GE'=> "Laufende Abstransport"),
	'EXPEDITEUR'=> array(	
		'FR'=> "Expéditeur",
		'UK'=> "Shipper",
		'GE'=> "Absender"),
	'F'=> array(
		'FR'=> "Femme",
		'UK'=> "Female",
		'GE'=> "Frau"),
	'FAMILLE'=> array(
		'FR'=> "Famille",
		'UK'=> "Family",
		'GE'=> "Familie"),
	'FAX'=> array(	
		'FR'=> "Fax",
		'UK'=> "Fax",
		'GE'=> "Telefax"),
	'FEMME'=> array(
		'FR'=> "Femme",
		'UK'=> "Female",
		'GE'=> "Frau"),
	'FERME_LIT'=> array(
		'FR'=> "Fermeture de lits",
		'UK'=> "bed closures",
		'GE'=> "Bettschliessung"),
	'FIN_SESSION'=> array(	
		'FR'=> "Fin de la session ",
		'UK'=> "End of the session ",
		'GE'=> "Ende der Sitzung "),
	'FIN_SESSION_IMPOSSIBLE'=> array(	
		'FR'=> "Impossible de mettre fin à la session ",
		'UK'=> "Impossible to put an end to the session ",
		'GE'=> "Unmöglich die Sitzung zu beenden "),
	'FOURNISSEUR'=> array(
		'FR'=> "Fournisseur",
		'UK'=> "Supplier",
		'GE'=> "Lieferant"),
	'FOURNITURES'=> array(
		'FR'=> "Fournitures",
		'UK'=> "Supplies",
		'GE'=> "Lieferungen"),
	'FPT'=> array(
		'FR'=> "Fourgon pompe tonne",
		'UK'=> "Pumper",
		'GE'=> "Tanklöschfahrzeug"),
	'FRANCAIS'=> array(
		'FR'=> "Français",
		'UK'=> "French",
		'GE'=> "Französich"),
	'FRANCE'=> array(	
		'FR'=> "France",
		'UK'=> "France",
		'GE'=> "Franckreich"),
	'GRAVITE'=> array(	
		'FR'=> "Gravité",
		'UK'=> "Seriousness",
		'GE'=> "Schwere"),
	'GESTION_INTERVENANT'=> array(	
		'FR'=> "Gestion des Intervenants",
		'UK'=> "Responder's management",
		'GE'=> "Personalverwaltung"),
	'GESTION_LITS'=> array(
		'FR'=> "SAGEC 67 - GESTION DES LITS",
		'UK'=> "SAGEC 67 - MANAGEMENT OF THE BEDS",
		'GE'=> "SAGEC 67 - VERWALTUNG DER BETTEN"),
	'GESTION_UTILISATEUR'=> array(	
		'FR'=> "Gestion des utilisateurs",
		'UK'=> "User's management",
		'GE'=> "Verwaltung der Benutzer"),
	'GESTION_VECTEURS'=> array(	
		'FR'=> "SAGEC 67 - GESTION DES VECTEURS",
		'UK'=> "SAGEC 67 - MANAGEMENT OF THE VECTORS",
		'GE'=> "SAGEC 67 - VERWALTUNG DER VEKTOREN"),
	'GESTION_VICTIMES'=> array(	
		'FR'=> "SAGEC 67 - GESTION DES VICTIMES",
		'UK'=> "SAGEC 67 - MANAGEMENT OF THE VICTIMS",
		'GE'=> "SAGEC 67 - VERWALTUNG DER OPFNER"),
	'H'=> array(	
		'FR'=> "Homme",
		'UK'=> "Male",
		'GE'=> "Man"),
	'HELICOPTERE'=> array(	
		'FR'=> "Hélicoptère",
		'UK'=> "Helicopter",
		'GE'=> "Hubschrauber"),
	'HEURE_ALERTE'=> array(	
		'FR'=> "Heure d'alerte",
		'UK'=> "Warning hour",
		'GE'=> "Alarm Uhrzeit"),
	'HOMME'=> array(	
		'FR'=> "Homme",
		'UK'=> "Male",
		'GE'=> "Man"),
	'HOPITAL'=> array(
		'FR'=> "Hôpital",
		'UK'=> "Hospital",
		'GE'=> "Krankenhaus",
		'CH'=> "Spital"),
	'HOPITAUX'=> array(
		'FR'=> "Hôpitaux",
		'UK'=> "Hospitals",
		'GE'=> "Krankenhäuser"),
	'HOPITAUX_CREATION'=> array(
		'FR'=> "Hôpitaux - Création & Mise à jour",
		'UK'=> "Hospitals - New & Update",
		'GE'=> "Krankenhäuser - Neue & Aktualisierung"),
	'HUS'=> array(
		'FR'=> "Hôpitaux Universitaires de Strasbourg",
		'UK'=> "University Hospital of Strasbourg",
		'GE'=> "Universitätsklinikum Straßburg "),
	'IM'=> array(
		'FR'=> "IM",
		'UK'=> "IM",
		'GE'=> "IM"),
	'INTRODUCTION'=> array(
		'FR'=> "Introduction",
		'UK'=> "Introduction",
		'GE'=> "Einführung"),
	'INVITES'=> array(
		'FR'=> "Invités",
		'UK'=> "Guests",
		'GE'=> "Gâste"),
	'IO'=> array(
		'FR'=> "IO",
		'UK'=> "IO",
		'GE'=> "IO"),
	'IT'=> array(
		'FR'=> "IT",
		'UK'=> "IT",
		'GE'=> "IT"),
	'IV'=> array(
		'FR'=> "IV",
		'UK'=> "IV",
		'GE'=> "IV"),
	'JOURNEE_DU'=> array(
		'FR'=> "Journée du ",
		'UK'=> "Day of ",
		'GE'=> "Tag von "),
	'GERER_HOPITAL'=> array(
		'FR'=> "Gestion de services hospitaliers",
		'UK'=> "Management of hospital departments",
		'GE'=> "Stationsverwaltung"),
	'GYN-OBST'=> array(
		'FR'=> "GYN-OBST",
		'UK'=> "GYN-OBST",
		'GE'=> "GYN-OBST"),
	'HOSPITALISE'=> array(	
		'FR'=> "Hospitalisés",
		'UK'=> "Hospitalized",
		'GE'=> "In ein Krankenhaus eingeliefert"),
	'IDENTIFIANT'=> array(	
		'FR'=> "Identifiant",
		'UK'=> "Identifier",
		'GE'=> "Bezeichnung"),
	'IDENTIFIANT_NO'=> array(
		'FR'=> "N° d'identification",
		'UK'=> "identification number",
		'GE'=> "Registriernummer"),
	'IDENTIFICATION'=> array(
		'FR'=> "Identification",
		'UK'=> "Identification",
		'GE'=> "Identifizierung"),
	'IDENTIFIER_PRODUIT'=> array(
		'FR'=> "Identifier un produit chimique",
		'GE'=> "Ein Chemieprodukt identifizieren",
		'UK'=> "Identify a chemical"),
	'IMMATRICULATION'=> array(	
		'FR'=> "Immatriculation",
		'UK'=> "Registration",
		'GE'=> "Immatrikulation"),
	'INDICATIF'=> array(	
		'FR'=> "Indicatif",
		'UK'=> "Call sign",
		'GE'=> "Rufzeichen"),
	'INDISPONIBLE'=> array(
		'FR'=> "Indisponible",
		'UK'=> "Inalienable",
		'GE'=> "Nicht verfügbar"),
	'INFORMATION'=> array(
		'FR'=> "Informations",
		'UK'=> "Information",
		'GE'=> "Informationen"),
	'INFORMATION_SERVICE'=> array(
		'FR'=> "Informations sur le service",
		'UK'=> "Information on the ward",
		'GE'=> "Informationen über den Station"),
	'INTERVENANTS'=> array(	
		'FR'=> "Intervenants ",
		'UK'=> "actor ",
		'GE'=> "Beteiligter "),
	'INTERVENANT_NOUVEAU'=> array(	
		'FR'=> "Nouvel intervenant",
		'UK'=> "New actor ",
		'GE'=> "Neuer Beteiligter "),
	'INTERVENANT_MODIFIER'=> array(	
		'FR'=> "Modifier un intervenant",
		'UK'=> "To modify a actor",
		'GE'=> "Einen Beteiligter ändern"),
	'IRM'=> array(	
		'FR'=> "IRM",
		'UK'=> "MRI",
		'GE'=> "Kernspinresonanz"),
	'ISOLEMENT'=> array(	
		'FR'=> "ISOLEMENT",
		'UK'=> "ISOLATION",
		'GE'=> "EINZELN"),
	'LANGUE'=> array(	
		'FR'=> "french",
		'UK'=> "english",
		'GE'=> "german"),
	'LESIONS'=> array(	
		'FR'=> "Lésions",
		'UK'=> "Injuries",
		'GE'=> "Verletzungen"),
	'LIREBN'=> array(	
		'FR'=> "Lire le contenu du bloc-notes",
		'UK'=> "To see the contents of the scratch pad",
		'GE'=> "Den Inhalt des Notizblocks lesen"),
	'LISTE_SERVICE'=> array(	
		'FR'=> "Liste des services",
		'UK'=> "List services",
		'GE'=> "Liste der Dienste"),
	'LISTE_SERVICE_HOPITAL'=> array(	
		'FR'=> "Liste des services et des lits d'un hôpital",
		'UK'=> "List services and beds of a hospital",
		'GE'=> "Liste der Dienste und der Betten eines Krankenhauses"),
	'LISTE'=> array(	
		'FR'=> "Liste",
		'UK'=> "List",
		'GE'=> "Liste"),
	'LITS'=> array(
		'FR'=> "Lits ",
		'UK'=> "Beds ",
		'GE'=> "Betten "),
	'LITS_ADULTES'=> array(
		'FR'=> "Lits adultes",
		'UK'=> "Adults beds",
		'GE'=> "Erwachsenenbett"),
	'LITS_AUTO'=> array(
		'FR'=> "Lits installés",
		'UK'=> "Authorized beds",
		'GE'=> "Berechtigten Betten"),
	'LITS_ENFANTS'=> array(
		'FR'=> "Lits enfants",
		'UK'=> "Childs beds",
		'GE'=> "Kinderbett"),
	'LITS_FERME'=> array(
		'FR'=> "Lits fermés",
		'UK'=> "Closed beds",
		'GE'=> "Geschlossenen Betten"),
	'LITS_INSTALLE'=> array(
		'FR'=> "Lits installés",
		'UK'=> "Installed beds",
		'GE'=> "Angelegten Betten"),
	'LITS_OCC'=> array(
		'FR'=> "Lits occupés",
		'UK'=> "occupied beds",
		'GE'=> "besetze Betten"),
	'LITS_RESERVE'=> array(
		'FR'=> "Lits réservés",
		'UK'=> "Reserved beds",
		'GE'=> "Reservierten Betten"),
	'LITS_LIB'=> array(
		'FR'=> "Lits libérables",
		'UK'=> "Released beds",
		'GE'=> "Betten befreit"),
	'LITS_SUP'=> array(	
		'FR'=> "Lits sup.",
		'UK'=> "Additional beds",
		'GE'=> "Zusätzlichen Betten"),
	'LITS_DISPO'=> array(
		'FR'=> "Lits disponibles",
		'UK'=> "Beds available",
		'GE'=> "Verfügbaren Betten"),
	'LITS_ISOLEMENT'=> array(
		'FR'=> "Lits en isolement",
		'UK'=> "Quarantine beds",
		'GE'=> "Isolierbetten"),
	'LITS_REA'=> array(
		'FR'=> "Lits de réanimation",
		'UK'=> "Intensive beds",
		'GE'=> "Intensivpflege Betten"),
	'LITS_RESPI'=> array(
		'FR'=> "Lits avec respirateurs",
		'UK'=> "Beds with respirators",
		'GE'=> "Betten mit beatmungsapparaten"),
	'LITS_SANS_RESPI'=> array(
		'FR'=> "Lits sans respirateurs",
		'UK'=> "Beds without respirators",
		'GE'=> "Betten ohne beatmungsapparat"),
	'LONG_SEJOUR'=> array(
		'FR'=> "Long séjour",
		'UK'=> "Long séjour",
		'GE'=> "Long séjour"),
	'LOCALISATION'=> array(
		'FR'=> "Localisation",
		'UK'=> "Localisation",
		'GE'=> "Lokalisation"),
	'LOCALISATION_CONTACT'=> array(
		'FR'=> "Localisation du contact",
		'UK'=> "Localization of the contact",
		'GE'=> "Lokalisierung des Kontaktes"),
	'LOGISTIQUE'=> array(
		'FR'=> "Véhicule logistique",
		'UK'=> "Logistics",
		'GE'=> "Logistics"),
	'LOT'=> array(
		'FR'=> "Lot",
		'UK'=> "Batch",
		'GE'=> "Teil"),
	'LSP'=> array(	
		'FR'=> "Laissés sur place",
		'UK'=> "Not hospitalized",
		'GE'=> "Nicht in ein Krankenhaus eingeliefert"),
	'MAIL'=> array(
		'FR'=> "Couriel",
		'UK'=> "Mail",
		'GE'=> "Mail"),
	'MAIN'=> array(
		'FR'=> "Main",
		'UK'=> "Hand",
		'GE'=> "Hand"),
	'MATERIEL_DISPO'=> array(
		'FR'=> "Matériel disponible",
		'UK'=> "Available material",
		'GE'=> "Verfügbares Material"),
	'MAXILLO'=> array(
		'FR'=> "Chir.Maxillo-Faciale",
		'UK'=> "Maxillo-facial surgery",
		'GE'=> "Maxillo-Gesichtschirurgie"),
	'MESSAGE'=> array(	
		'FR'=> "Message",
		'UK'=> "Message",
		'GE'=> "Mitteilung"),
	'MAJ'=> array(
		'FR'=> "Mise à jour",
		'UK'=> "Update",
		'GE'=> "Aktualisierung"),
	'MAJ_LIT_HOP'=> array(
		'FR'=> "Mise à jour lits/hôpitaux",
		'UK'=> "Update beds/hospitals",
		'GE'=> "Aktualisierung Betten/Krankenhaus"),
	'MATERIEL_DISPO'=> array(
		'FR'=> "Matériel disponible",
		'UK'=> "Available material",
		'GE'=> "Verfügbares Material"),
	'MEDECINE'=> array(
		'FR'=> "MEDECINE",
		'UK'=> "MEDICINE",
		'GE'=> "MEDIZIN"),
	'MEDIA'=> array(
		'FR'=> "Media",
		'UK'=> "Media",
		'GE'=> "Medien"),
	'MEDICALISE'=> array(
		'FR'=> "médicalisée",
		'UK'=> "with a doctor",
		'GE'=> "mit Notartz"),
	'MENU_PRINCIPAL'=> array(	
		'FR'=> "Menu",
		'UK'=> "Main menu",
		'GE'=> "Menu"),
	'MESSAGE'=> array(	
		'FR'=> "Message",
		'UK'=> "Message",
		'GE'=> "Mitteilung"),
	'MINIBUS'=> array(	
		'FR'=> "Minibus",
		'UK'=> "Minibus",
		'GE'=> "Minibus"),
	'MODIFIER'=> array(
		'FR'=> "Modifier",
		'UK'=> "modify",
		'GE'=> "ändern"),
	'MODIF'=> array(
		'FR'=> "Les modifications ne seront prises en compte qu'après validation",
		'UK'=> "The modifications will be taken into account only after validation",
		'GE'=> "Die Änderungen werden nur nach Bestätigung berücksichtigt sein"),
	'MODIFIER_LANGUE'=> array(	
		'FR'=> "Modifier la langue",
		'UK'=> "To modify the language",
		'GE'=> "Die Sprache ändern"),
	'MODIFIER_CONTACT'=> array(	
		'FR'=> "Modifier un contact de",
		'UK'=> "To modify a contact of",
		'GE'=> "Einen Kontakt ändern von"),
	'MODIFIER_ORGANISME'=> array(	
		'FR'=> "Modifier un Organisme",
		'UK'=> "Modify an organization",
		'GE'=> "Organisation zu ändern"),
	'MORGUE'=> array(	
		'FR'=> "Morgue",
		'UK'=> "Mortuary",
		'GE'=> "Leichenhalle"),
	'MOYENS_DISPONIBLES'=> array(	
		'FR'=> "Moyens disponibles",
		'UK'=> "Means avalaible",
		'GE'=> "Verfügbare Mittel"),
	'MOYENS_ENGAGES'=> array(
		'FR'=> "Moyens engagés",
		'UK'=> "Means engaged",
		'GE'=> "Engagierte Mittel"),
	'MOYENS_SPECIFIQUES'=> array(
		'FR'=> "Moyens spécifiques",
		'UK'=> "Specific means",
		'GE'=> "Spezifische Mittel"),
	'MR'=> array(
		'FR'=> "Maison de retraite",
		'UK'=> "old people's home",
		'GE'=> "Altenheim"),
	'MSG_IDENTIFICATION'=> array(
		'FR'=> "Vous devez vous identifier ",
		'UK'=> "You must be identified",
		'GE'=> "Sie müssen sich identifizieren"),
	'MSG_SITE_ACCESSIBLE'=> array(	
		'FR'=> "Le site n'est pas accessible",
		'UK'=> "Internet site is not accessible",
		'GE'=> "Die Internet-Adresse ist nicht zugänglich"),
	'NE_LE'=> array(
		'FR'=> "Né(e) le",
		'UK'=> "Born the",
		'GE'=> "Geboren die"),
	'NATURE'=> array(
		'FR'=> "Nature",
		'UK'=> "Nature",
		'GE'=> "Natur"),
	'NATURE_CONTACT'=> array(
		'FR'=> "Nature du contact",
		'UK'=> "Nature of the contact",
		'GE'=> "Natur des Kontaktes"),
	'NEUROCHIR'=> array(
		'FR'=> "Neuro-Chirurgie",
		'UK'=> "Neuro_Surgery",
		'GE'=> "Neurochirurgie"),
	'NO_SESSION'=> array(	
		'FR'=> "Il n'y a pas de session ouverte",
		'UK'=> "There is no open session",
		'GE'=> "Es gibt keine eröffnete Sitzung"),
	'NO_SELECT'=> array(	
		'FR'=> "Pas de sélection",
		'UK'=> "No selection",
		'GE'=> "Keine Auswahl"),
	'NOM'=> array(	
		'FR'=> "Nom",
		'UK'=> "Name",
		'GE'=> "Name"),
	'NON'=> array(	
		'FR'=> "Non",
		'UK'=> "No",
		'GE'=> "Nein"),
	'NON_ALERTE'=> array(	
		'FR'=> "Non Alerté",
		'UK'=> "not alerted",
		'GE'=> "Nicht alarmiert"),
	'NON_MEDICALISE'=> array(
		'FR'=> "non médicalisée",
		'UK'=> "without a doctor",
		'GE'=> "ohne Notartz"),
	'NOMBRE_DE'=> array(	
		'FR'=> "Nombre de ",
		'UK'=> "Number of ",
		'GE'=> "Zahl der "),
	'NOMBRE_DE_DECES'=> array(	
		'FR'=> "Nombre de décès",
		'UK'=> "Number of deaths",
		'GE'=> "Zahl des Todes"),
	'NOMBRE_DE_DECES_75'=> array(	
		'FR'=> "Nombre de décès de plus de 75 ans",
		'UK'=> "Number of deaths of more than 75 years",
		'GE'=> "Zahl des Todes von mehr als 75 Jahren"),
	'NOUVEAU'=> array(
		'FR'=> "Nouveau",
		'UK'=> "New",
		'GE'=> "Neues"),
	'NOUVEAU_CONTACT'=> array(
		'FR'=> "Nouveau contact pour",
		'UK'=> "New contact for",
		'GE'=> "Neues Kontact für"),
	'NOUVEAU_PATIENT'=> array(	
		'FR'=> "Nouveau patient",
		'UK'=> "New patient",
		'GE'=> "Neuer Patient"),
	'OFFRE_SOINS'=> array(
		'FR'=> "Offre de soins",
		'UK'=> "Care's offer",
		'GE'=> "Behandlungsangebot"),
	'OPHTALMO'=> array(
		'FR'=> "Ophtalmologie",
		'UK'=> "Ophthalmology",
		'GE'=> "Augenheilkunde"),
	'ORL'=> array(
		'FR'=> "ORL",
		'UK'=> "ORL",
		'GE'=> "ORL"),
	'ORTHOPEDIE'=> array(
		'FR'=> "Orthopédie",
		'UK'=> "Orthopaedics",
		'GE'=> "Orthopädie"),
	'OUI'=> array(
		'FR'=> "Oui",
		'UK'=> "Yes",
		'GE'=> "Ya"),
	'OU'=> array(
		'FR'=> "ou",
		'UK'=> "or",
		'GE'=> "or"),
	'ORIGINE'=> array(
		'FR'=> "Source",
		'UK'=> "Organization",
		'GE'=> "Herkunft"),
	'ORGANISME'=> array(
		'FR'=> "Organisme",
		'UK'=> "Organization",
		'GE'=> "Organisation"),
	'PAR'=> array(	
		'FR'=> "par",
		'UK'=> "by",
		'GE'=> "durch"),
	'PATIENT_ACCEPTE'=> array(	
		'FR'=> "Patients acceptés",
		'UK'=> "accepted patients",
		'GE'=> "akzeptierte Patienten"),
	'PAYS'=> array(	
		'FR'=> "Pays",
		'UK'=> "Country",
		'GE'=> "Land"),
	'PC'=> array(
		'FR'=> "PC",
		'UK'=> "PC",
		'GE'=> "PC"),
	'PCMOBILE'=> array(	
		'FR'=> "Véhicule PC",
		'UK'=> "Command car",
		'GE'=> "Command car"),
	'PDS'=> array(
		'FR'=> "PDS",
		'UK'=> "GP",
		'GE'=> "Hausärztlicher Notdienst"),
	'PED'=> array(
		'FR'=> "PEDIATRIE",
		'UK'=> "PEDIATRY",
		'GE'=> "PÄDIATRIE"),
	'PEREMPTION'=> array(
		'FR'=> "Péremption",
		'UK'=> "Lapsing",
		'GE'=> "Verjährung"),
	'PERSONNE'=> array(
		'FR'=> "Personne",
		'UK'=> "People",
		'GE'=> "Person"),
	'PERSONNEL'=> array(
		'FR'=> "Personnel",
		'UK'=> "People",
		'GE'=> "Personal"),
	'PERSONNEL_DISPO'=> array(
		'FR'=> "Personnel disponible",
		'UK'=> "Available staff",
		'GE'=> "Verfügbares Personal"),
	'PET_SCAN'=> array(
		'FR'=> "Pet Scan",
		'UK'=> "Pet Scan",
		'GE'=> "Pet Scan"),
	'PLACES'=> array(
		'FR'=> "Places",
		'UK'=> "Places",
		'GE'=> "Plätze"),
	'PLACES_DISPO'=> array(
		'FR'=> "places disponibles",
		'UK'=> "Places free",
		'GE'=> "freien Plätze"),
	'PLACES_AUTO'=> array(
		'FR'=> "places autorisées",
		'UK'=> "Authorized places",
		'GE'=> "Berechtigten Plätze"),
	'PLATEAU'=> array(
		'FR'=> "Plateaux Techniques",
		'UK'=> "Plateaux Techniques",
		'GE'=> "Plateaux Techniques"),
	'PMA'=> array(
		'FR'=> "PMA",
		'UK'=> "advanced medical station",
		'GE'=> "Fortgeschrittener medizinischer Posten"),
	'PO'=> array(
		'FR'=> "PO",
		'UK'=> "PO",
		'GE'=> "PO"),
	'POLYTRAU'=> array(
		'FR'=> "Polytraumarisé",
		'UK'=> "Trauma",
		'GE'=> "Polytrauma"),
	'POSITION'=> array(
		'FR'=> "Position",
		'UK'=> "Position",
		'GE'=> "Lage"),
	'POSSIBILITE'=> array(
		'FR'=> "Possibilités",
		'UK'=> "Possibilities",
		'GE'=> "Möglichkeiten"),
	'POSTE_SAISIE'=> array(
		'FR'=> "Poste de saisie ",
		'UK'=> "Input unit ",
		'GE'=> "Posten der Erfassung "),
	'POUR_SERVICE'=> array(
		'FR'=> "Pour les services qui en disposent:",
		'UK'=> "For the wards which have it:",
		'GE'=> "Für die Station, die es haben:"),
	'PRE'=> array(	
		'FR'=> "PRE",
		'UK'=> "Evacuation",
		'GE'=> "Abstransport"),
	'PRENOM'=> array(
		'FR'=> "Prénom",
		'UK'=> "First name",
		'GE'=> "Vorname"),
	'PRESENTATION'=> array(
		'FR'=> "Présentation",
		'UK'=> "Présentation",
		'GE'=> "Presentation"),
	'PRESSION_ART'=> array(
		'FR'=> "Pression artérielle",
		'UK'=> "Arterial pressure",
		'GE'=> "Blutdruck"),
	'PA_SYST'=> array(
		'FR'=> "Pression Systolique",
		'UK'=> "Systolic blood pressure",
		'GE'=> "Systolicher Blutdruck"),
	'PA_DIAST'=> array(
		'FR'=> "Pression diastolique",
		'UK'=> "Diastolic blood pressure",
		'GE'=> "Diastolicher Blutdruck"),
	'PRIORITE_ALERTE'=> array(	
		'FR'=> "Priorité à l'alerte",
		'UK'=> "priority with alarm",
		'GE'=> "Priorität"),
	'PROFESSION'=> array(
		'FR'=> "Profession",
		'UK'=> "Occupation",
		'GE'=> "Beruf"),
	'PSY'=> array(
		'FR'=> "Psychiatrie",
		'UK'=> "Psychiatrie",
		'GE'=> "Psychiatrie"),
	'QUAD'=> array(
		'FR'=> "Quad",
		'UK'=> "Quad",
		'GE'=> "Quad"),
	'QUANTITE'=> array(
		'FR'=> "Quantité",
		'UK'=> "Quantity",
		'GE'=> "Menge"),
	'QUESTIONS'=> array(
		'FR'=> "Questions",
		'UK'=> "Questions",
		'GE'=> "Fragen"),
	'QUITTER'=> array(
		'FR'=> "Quitter",
		'UK'=> "To leave",
		'GE'=> "Verlassen"),
	'QUIT_SESSION'=> array(	
		'FR'=> "Quitter la session",
		'UK'=> "To leave the session",
		'GE'=> "Die Sitzung verlassen"),
	'RADIOANALOG'=> array(	
		'FR'=> "Radio analogique",
		'UK'=> "Anlogic radio",
		'GE'=> "Analoges Radio"),
	'RADIONUM'=> array(	
		'FR'=> "Radio numérique",
		'UK'=> "Numerical radio",
		'GE'=> "Numerisches Radio"),
	'RAPPEL'=> array(	
		'FR'=> "Rappel",
		'UK'=> "Recall",
		'GE'=> "Rückruf"),
	'RAYON'=> array(	
		'FR'=> "Se trouvant dans un rayon de",
		'UK'=> "is in a radius of",
		'GE'=> "befindet sich in einem radius von"),
	'REA'=> array(
		'FR'=> "REA",
		'UK'=> "ICU",
		'GE'=> "INTENSIVSTATION"),
	'REA_NEONAT'=> array(
		'FR'=> "Réa.néonatale",
		'UK'=> "Newborn intensive station",
		'GE'=> "Neugeb.Intensiv Station"),
	'REA_PED'=> array(
		'FR'=> "REA PED",
		'UK'=> "PICU",
		'GE'=> "PÄDIATRISCHE INTENSIVSTATION"),
	'RECAPITULATIF'=> array(
		'FR'=> "Récapitulatif",
		'UK'=> "Summary",
		'GE'=> "Zusammenfassung"),
	'RECAPITULATIF_LOCAL'=> array(
		'FR'=> "Récapitulatif local",
		'UK'=> "Local summary",
		'GE'=> "Lokal Zusammenfassung"),
	'RECAPITULATIF_REGIONAL'=> array(
		'FR'=> "Récapitulatif régional",
		'UK'=> "Regional summary",
		'GE'=> "Regional Zusammenfassung"),
	'RECHERCHER'=> array(
		'FR'=> "Rechercher",
		'UK'=> "Find it",
		'GE'=> "Suchen"),
	'REGULATION'=> array(
		'FR'=> "Régulation",
		'UK'=> "Call Center",
		'GE'=> "Litstelle"),
	'REINIT_SESSION'=> array(	
		'FR'=> "Réinitialiser une session",
		'UK'=> "To initialize a new session",
		'GE'=> "Eine Sitzung neu zu initialisieren"),
	'RESPI_DISPO'=> array(
		'FR'=> "Nombre de respirateurs disponibles",
		'UK'=> "Number of respirators available",
		'GE'=> "Zahl der verfügbaren Atmungsapparate"),
	'RETOUR'=> array(
		'FR'=> "Retour",
		'UK'=> "Back",
		'GE'=> "Zurück"),
	'REVEIL'=> array(	
		'FR'=> "REVEIL",
		'UK'=> "AWAKE ROOM",
		'GE'=> "AUFWACHRAUM"),
	'SAGEC67'=> array(	
		'FR'=> "Système d'Aide à la Gestion d'Evènements Catastrophiques",
		'UK'=> "System of Assistance to the Management of Catastrophic Events",
		'GE'=> "Hilfsprogramm zum Management von Katastrophen"),
		//'GE'=> "Beihilferegelung für die Verwaltung verhängnisvoller Ereignisse"),
	'SAISIE_RAPIDE'=> array(
		'FR'=> "Saisie rapide",
		'UK'=> "Fast input",
		'GE'=> "Schnelle Erfassung"),
	'SAMU'=> array(
		'FR'=> "SAMU",
		'UK'=> "EMERGENCY CALL CENTER",
		'GE'=> "Leitstelle"),
	'SAU'=> array(
		'FR'=> "SAU",
		'UK'=> "EMERGENCY",
		'GE'=> "NOTAUFNAHME"),
	'SC'=> array(
		'FR'=> "SC",
		'UK'=> "SC",
		'GE'=> "SC"),
	'SCANNER'=> array(	
		'FR'=> "Scanner",
		'UK'=> "CT Scan",
		'GE'=> "Scanner"),
	'SELECTION'=> array(
		'FR'=> "Sélection",
		'UK'=> "Selection",
		'GE'=> "Auswahl"),
	'SELECTIONNER_COMMUNE'=> array(	
		'FR'=> "Sélectionner une commune",
		'UK'=> "Choose a town",
		'GE'=> "Auszuwählen eine Stadt"),
	'SELECTIONNER_HOPITAL'=> array(	
		'FR'=> "Sélectionner un hôpital",
		'UK'=> "Choose a hospital",
		'GE'=> "Auszuwählen ein Krankenhaus"),
	'SELECTIONNER_INTERVENANT'=> array(	
		'FR'=> "Sélectionner un intervenant",
		'UK'=> "Personnel select",
		'GE'=> "Einen Personal auswählen"),
	'SELECTIONNER_ORGANISME'=> array(	
		'FR'=> "Sélectionner un organisme",
		'UK'=> "to select an organization",
		'GE'=> "eine Organisation auszuwählen"),
	'SELECTIONNER_SERVICE'=> array(	
		'FR'=> "Sélectionner un service",
		'UK'=> "Choose a ward",
		'GE'=> "Auszuwählen ein Station"),
	'SELECTIONNER_VECTEUR'=> array(	
		'FR'=> "Sélectionner un vecteur",
		'UK'=> "Select a vector",
		'GE'=> "Einen Vektor auswählen"),
	'SELECT_HOPITAL'=> array(	
		'FR'=> "Sélectionnez un hôpital",
		'UK'=> "Select a hospital",
		'GE'=> "Wählen Sie ein Krankenhaus aus"),
	'SELECT_SERVICE'=> array(	
		'FR'=> "Sélectionnez un service",
		'UK'=> "Select a service",
		'GE'=> "Wählen Sie eine Krankenhausstation aus"),
	'SERVICE'=> array(
		'FR'=> "Service",
		'UK'=> "Ward",
		'GE'=> "Station"),
	'SERVICE_ALERTE'=> array(	
		'FR'=> "Service alerté",
		'UK'=> "alerted service",
		'GE'=> "Station benachrichtig"),
	'SERVICE_CREATION'=> array(
		'FR'=> "Services - Création & Mise à jour",
		'UK'=> "Services - New & Update",
		'GE'=> "Station - Neue & Aktualisierung"),
	'SERVICE_FERME'=> array(
		'FR'=> "Services fermes",
		'UK'=> "Closed Services",
		'GE'=> "Cloded Station"),
	'SERVICE_NOM'=> array(
		'FR'=> "Nom du service",
		'UK'=> "Service name",
		'GE'=> "Name des Station"),
	'SESSION_LOGIN'=> array(
		'FR'=> "Identifiant: ",
		'UK'=> "Login: ",
		'GE'=> "Bezeichner: "),
	'SESSION_PASSWORD'=> array(
		'FR'=> "Mot de passe: ",
		'UK'=> "Password: ",
		'GE'=> "Passwort: "),
	'SESSION_IDENTIFICATION'=> array(	
		'FR'=> "IDENTIFICATION ",
		'UK'=> "IDENTIFICATION ",
		'GE'=> "ERKENNUNG: "),
	'SEULEMENT'=> array(	
		'FR'=> "Seulement",
		'UK'=> "Only",
		'GE'=> "Nur"),
	'SEXE'=> array(	
		'FR'=> "Sexe",
		'UK'=> "Sex "),
	'SI'=> array(	
		'FR'=> "Soins Intensifs",
		'UK'=> "SI ",
		'GE'=> "SI"),
	'SIGNES_PARTICULIERS'=> array(	
		'FR'=> "Signes particuliers",
		'UK'=> "Distinguishing marks ",
		'GE'=> "Besondere Zeichen"),
	'SITE_INTERNET'=> array(	
		'FR'=> "Site internet",
		'UK'=> "Internet",
		'GE'=> "Internet"),
	'SMUR'=> array(
		'FR'=> "SMUR",
		'UK'=> "MICU",
		'GE'=> "Notartz Wagen"),
	'SOINS_SUITE'=> array(
		'FR'=> "Soins de suite",
		'UK'=> "Subsequent care",
		'GE'=> "Folgepflege"),
	'SPECIALITE'=> array(	
		'FR'=> "Spécialité ",
		'UK'=> "Spéciality ",
		'GE'=> "Specialität"),
	'STATISTIQUES'=> array(	
		'FR'=> "Statistiques ",
		'UK'=> "Statistics ",
		'GE'=> "Statistiken"),
	'STROKE'=> array(	
		'FR'=> "Unité Neuro-Vasculaire",
		'UK'=> "Stroke Center",
		'GE'=> "Stroke Center"),
	'SUISSE'=> array(	
		'FR'=> "Suisse",
		'UK'=> "Swiss",
		'GE'=> "Schweiz"),
	'SUPPRIMER'=> array(	
		'FR'=> "Supprimer",
		'UK'=> "Delete",
		'GE'=> "Abschaffen"),
	'SUR PLACE'=> array(	
		'FR'=> "Sur place",
		'UK'=> "Sur place",
		'GE'=> "Sur place"),
	'SYNOPTIQUE'=> array(
		'FR'=> "Synoptique",
		'UK'=> "Synoptic",
		'GE'=> "Übersichtstafel"),
	'SYNOPTIQUE_LITS_DISPO'=> array(
		'FR'=> "Synoptique des lits disponibles",
		'UK'=> "Synoptic of the beds available",
		'GE'=> "Übersichtstafel der verfügbaren Betten"),
	'SYNTHESE'=> array(
		'FR'=> "Synthèse",
		'UK'=> "Synthesis",
		'GE'=> "Synthese"),
	'TABLES'=> array(
		'FR'=> "Table",
		'UK'=> "Table",
		'GE'=> "Verzeichnis"),
	'TABLEAU_RECAP'=> array(
		'FR'=> "Tableau récapitulatif",
		'UK'=> "Summary Table",
		'GE'=> "Übersichtstabelle"),
	'TEL'=> array(
		'FR'=> "Tel",
		'UK'=> "Phone",
		'GE'=> "Telefon"),
	'TEL_FIXE'=> array(
		'FR'=> "Tel. fixe",
		'UK'=> "Phone",
		'GE'=> "Festnetztelefon"),
	'TEL_MOBILE'=> array(
		'FR'=> "Tel. mobile",
		'UK'=> "Mobile Phone",
		'GE'=> "Mobiltelefon"),
	'TEL_PORTABLE'=> array(
		'FR'=> "Tel. portable",
		'UK'=> "Portable Phone",
		'GE'=> "Handy"),
	'TEL_SATELLITE'=> array(
		'FR'=> "Tel. satellite",
		'UK'=> "Satellite Phone",
		'GE'=> "Satellitentelefon"),
	'TENDANCE'=> array(
		'FR'=> "Tendances",
		'UK'=> "Tendencies",
		'GE'=> "Tendenzen"),
	'TRI'=> array(	
		'FR'=> "Tri",
		'UK'=> "Triage",
		'GE'=> "Sortieren"),
	'TRIE_PAR'=> array(	
		'FR'=> "Trié par",
		'UK'=> "Sorted by",
		'GE'=> "Sortiert nach"),
	'TYPE'=> array(	
		'FR'=> "type",
		'UK'=> "kind of",
		'GE'=> "Typus"),
	'TOTAL'=> array(	
		'FR'=> "Total",
		'UK'=> "Total",
		'GE'=> "Gesamtzahl"),
	'TOUS'=> array(	
		'FR'=> "Tous",
		'UK'=> "All",
		'GE'=> "Alle"),
	'TOTAL_LITS'=> array(
		'FR'=> "Total lits",
		'UK'=> "total beds",
		'GE'=> "Bettgesamtzahl"),
	'TOTAL_LITS_DISPO'=> array(
		'FR'=> "Total des lits disponibles",
		'UK'=> "Total of the beds available",
		'GE'=> "Gesamtzahl der verfügbaren Betten"),
	'TOTAL_SPECIALITE'=> array(
		'FR'=> "Total par spécialités",
		'UK'=> "Total by specialities",
		'GE'=> "Gesamtzahl von Spezialitäten"),
	'TRAITEMENTS'=> array(	
		'FR'=> "Traitements",
		'UK'=> "Treatments",
		'GE'=> "Behandlungen"),
	'TRANSPORT'=> array(	
		'FR'=> "Transport",
		'UK'=> "Transport",
		'GE'=> "Transport"),
	'TRANSPORT_NON_MEDICALISE'=> array(	
		'FR'=> "Transport non médicalisé",
		'UK'=> "No medicalized transport",
		'GE'=> "Nicht Medizinischer Transport"),
	'TRANSPORT_MEDICALISE'=> array(	
		'FR'=> "Transport médicalisé",
		'UK'=> "Medicalized transport",
		'GE'=> "Medizinischer Transport"),
	'TRAUMATISME'=> array(	
		'FR'=> "Traumatisme",
		'UK'=> "Trauma",
		'GE'=> "Verletzung"),
	'TRAUMA_CRANE'=> array(	
		'FR'=> "Traumatisme crânien grave",
		'UK'=> "Head trauma",
		'GE'=> "Schädelverletzung"),
	'TRAUMATO'=> array(	
		'FR'=> "Traumatologie",
		'UK'=> "Traumatology",
		'GE'=> "Unfallchirurgie"),
	'TRAVAIL'=> array(	
		'FR'=> "Travail",
		'UK'=> "Working place",
		'GE'=> "Arbeitplatz"),
	'TYPE'=> array(	
		'FR'=> "Type",
		'UK'=> "Type",
		'GE'=> "Typ"),
	'TYPE_DE_MOYEN'=> array(	
		'FR'=> "Type de moyen",
		'UK'=> "Type of means",
		'GE'=> "Art von Mittel"),
	'TYPE_INTERVENANT'=> array(	
		'FR'=> "Type d'intervenant",
		'UK'=> "Type of responder",
		'GE'=> "Personaltyp"),
	'U'=> array(
		'FR'=> "U",
		'UK'=> "U",
		'GE'=> "T"),
	'UA'=> array(
		'FR'=> "UA",
		'UK'=> "UA",
		'GE'=> "T I"),
	'UR'=> array(
		'FR'=> "UR",
		'UK'=> "UR",
		'GE'=> "T II"),
	'U3'=> array(
		'FR'=> "U3",
		'UK'=> "U3",
		'GE'=> "T III"),
	'UF'=> array(
		'FR'=> "UF",
		'UK'=> "UF",
		'GE'=> "UF"),
	'DCD'=> array(
		'FR'=> "DCD",
		'UK'=> "Dead",
		'GE'=> "T IV"),
	'UMD'=> array(
		'FR'=> "Unité mobile de décontamination",
		'UK'=> "Decontamination mobile unit",
		'GE'=> "Decontamination mobile unit"),
	'UMH'=> array(
		'FR'=> "UMH",
		'UK'=> "UMH",
		'GE'=> "RTW"),
	'UNITE FONCTIONNELLE'=> array(
		'FR'=> "UF",
		'UK'=> "UF",
		'GE'=> "UF"),
	'UPATOU'=> array(	
		'FR'=> "UPATOU",
		'UK'=> "UPATOU",
		'GE'=> "UPATOU"),
	'USIC'=> array(	
		'FR'=> "USIC",
		'UK'=> "CCU",
		'GE'=> "KARDIOLOGIE"),
	'VALEUR'=> array(	
		'FR'=> "Valeur",
		'UK'=> "Value",
		'GE'=> "Wert"),
	'VALIDER'=> array(	
		'FR'=> "Envoyer",
		'UK'=> "Submit",
		'GE'=> "andern"), //Einloggen
	'VALEUR_CONTACT'=> array(	
		'FR'=> "Valeur du contact",
		'UK'=> "Value of the contact",
		'GE'=> "Wert des Kontaktes"),
	'VECTEURS'=> array(	
		'FR'=> "Vecteurs ",
		'UK'=> "Vectors ",
		'GE'=> "Verkehrsmittel "),
	'VECTEUR_NOUVEAU'=> array(	
		'FR'=> "Nouveau vecteur",
		'UK'=> "New vector",
		'GE'=> "Neuer Verkehrsmittel"),
	'VECTEUR_MODIFIER'=> array(	
		'FR'=> "Modifier un vecteur",
		'UK'=> "To modify a vector",
		'GE'=> "Einen Verkehrsmittel ändern"),
	'VICTIMES'=> array(	
		'FR'=> "Victimes ",
		'UK'=> "Victims ",
		'GE'=> "Verletzte "),
	'VICTIMES_CATA'=> array(	
		'FR'=> "Victimes catastrophe",
		'UK'=> "Disaster's victims",
		'GE'=> "Opfer der Katastrophe"),
	'VIDEOCONF'=> array(	
		'FR'=> "Vidéoconférence",
		'UK'=> "Videoconference",
		'GE'=> "Videokonferenz"),
	'VILLE'=> array(	
		'FR'=> "Ville",
		'UK'=> "City",
		'GE'=> "Stadt"),
	'VL'=> array(	
		'FR'=> "Véhicule léger",
		'UK'=> "Emergency car",
		'GE'=> "Retungswagen"),
	'VLHR'=> array(	
		'FR'=> "Véhicule de liaison Hors Route",
		'UK'=> "Véhicule de liaison Hors Route",
		'GE'=> "Véhicule de liaison Hors Route"),
	'VLINF'=> array(	
		'FR'=> "VL Infirmier",
		'UK'=> "Emergency nurse car",
		'GE'=> "Retungsschwesterwagen"),
	'VLM'=> array(	
		'FR'=> "VLM",
		'UK'=> "VLM",
		'GE'=> "NAW"),
	'VOIR'=> array(	
		'FR'=> "voir",
		'UK'=> "to see",
		'GE'=> "zu sehen"),
	'VPS'=> array(	
		'FR'=> "Véhicule premier secours",
		'UK'=> "First Emergency Car",
		'GE'=> "First Emergency Car"),
	'VSAV'=> array(	
		'FR'=> "VSAV",
		'UK'=> "VSAV",
		'GE'=> "VSAV"),
	'VSL'=> array(	
		'FR'=> "VSL",
		'UK'=> "VSL",
		'GE'=> "KrKw"),//Krankenkraftwagen
	'VTU'=> array(	
		'FR'=> "VTU",
		'UK'=> "VTU",
		'GE'=> "VTU"),
	'ZIP'=> array(	
		'FR'=> "Code postal",
		'UK'=> "Zip",
		'GE'=> "Postleitzahl"),
	'ZODIAC'=> array(	
		'FR'=> "Zodiac",
		'UK'=> "Ship",
		'GE'=> "Boot"),
);

?>
