<?php
// explications.php
print("<table border=\"1\">");
print("<TR>");
	print("<TD>Affaires</TD>");
	print("<TD>nombre d'appels ayant donné lieu à l'ouverture d'un dossier de régulation médicale</TD>");
print("</TR>");
print("<TR>");
	print("<TD>ASSU</TD>");
	print("<TD>nombre d'affaires ayant donné lieu à l'intervention d'une ambulance privée à la demande du SAMU</TD>");
print("</TR>");
print("<TR>");
	print("<TD>Conseils</TD>");
	print("<TD>nombre d'affaires ayant été traité par un conseil médical téléphonique</TD>");
print("</TR>");
print("<TR>");
	print("<TD>Entre 1 et 75</TD>");
	print("<TD>nombre de passages aux urgences pour des patients de plus de 1 an et moins de 75 ans</TD>");
print("</TR>");
print("<TR>");
	print("<TD>Hospitalisés</TD>");
	print("<TD>nombre de passages aux urgences ayant donné lieu à une hospitalisation (hors UHCD)</TD>");
print("</TR>");
print("<TR>");
	print("<TD>Médecins</TD>");
	print("<TD>nombre d'affaires ayant donné lieu à l'intervention d'un médecin généraliste à la demande du SAMU</TD>");
	print("<TR>");
	print("<TD>Moins de 1 an</TD>");
	print("<TD>nombre de passages aux urgences pour des patients de moins d'un an</TD>");
print("</TR>");
print("</TR>");
print("<TR>");
	print("<TD>Néonat</TD>");
	print("<TD>nombre d'affaires ayant donné lieu à un transport médicalisé d'un enfant de moins de 30 jours</TD>");
print("</TR>");
print("<TR>");
	print("<TD>Plus de 75 ans</TD>");
	print("<TD>nombre de passages aux urgences pour des patients de plus de 75 ans</TD>");
print("</TR>");
print("<TR>");
	print("<TD>Primaires</TD>");
	print("<TD>nombre d'affaires ayant donné lieu à l'intervention d'une équipe SMUR (hors transferts interhospitaliers)</TD>");
print("</TR>");
print("<TR>");
	print("<TD>Secondaires</TD>");
	print("<TD>nombre d'affaires ayant donné lieu à un transfert interhospitalier médicalisé par une équipe SMUR</TD>");
print("</TR>");
print("<TR>");
	print("<TD>Transferts</TD>");
	print("<TD>nombre de passages aux urgences ayant donné lieu à un transfert du patient vers un autre établissement de soins</TD>");
print("</TR>");
print("<TR>");
	print("<TD>TIIH</TD>");
	print("<TD>Transfert Infirmier Inter Hospitalier: nombre d'appels ayant donné lieu à un transfert interhospitalier réalisé sous la surveillance d'un(e) infirmier(e)</TD>");
print("</TR>");
print("<TR>");
	print("<TD>UHCD</TD>");
	print("<TD>nombre de passages aux urgences ayant donné lieu à une hospitalisation en Unité d'Hospitalisation de Courte Durée</TD>");
print("</TR>");
print("<TR>");
	print("<TD>VSAV</TD>");
	print("<TD>nombre d'affaires ayant donné lieu à l'intervention du SDIS à la demande du SAMU</TD>");
print("</TR>");
print("</table>");
?>