<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sun, 13 Sep 2009 16:43:51 +0200
 */
$conf['title'] = 'Sagec_doc';
$conf['lang'] = 'fr';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
